name: Téléchargement des données de la semaine, du jour et Publication des données augmentées

on:
  schedule:
      - cron: '0 0 * * 0'
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 139bercy/decp
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Installation des dépendances
      run: pip install pandas numpy geopy
    -   
      name: Téléchargement des références
      run: chmod +x get-data-weekly.sh && ./get-data-weekly.sh
    -
      name: Téléchargement de decp.json
      run: wget -O data/decp.json https://www.data.gouv.fr/fr/datasets/r/16962018-5c31-4296-9454-5998585496d2
    -
      name: Process
      run : python main.py 
    -
      name: Publication
      run: lftp -u ${{ secrets.LOG }}:${{ secrets.MDP }} ${{ secrets.SERV }} -e "set ftp:ssl-force true ; set ssl:verify-certificate false; cd decp; cd test; put results/decp_augmente.csv ; quit"
